# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: adapt

on: push

env: 
  MONGO_URL: ${{ secrets.MONGO_TEST_URL }}
  MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
  SECRETKEY: somesecret109248120938u109
  GOOGLE_CLOUD_PROJECT: adapt-348705
  GCLOUD_STORAGE_BUCKET: adaptstorage350
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint
    - run: npm run test
    
  frontend-checks:
      name: Frontend Checks
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
      steps:
        - uses: actions/checkout@v3
        - run: npm install
        - run: npm run lint
        - run: npm run test
  
  mobile-checks:
      name: Mobile Checks
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./adaPT-Mobile
      steps:
        - uses: actions/checkout@v3
        - run: npm install
        - run: npm run lint

  cypress-run:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [ backend-checks, frontend-checks ]
    steps:
    - uses: actions/checkout@v3
    - name: Run Backend Server
      working-directory: ./backend
      run: |
        npm install
        npm start &

    - name: Run Cypress
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./frontend
        wait-on: 'http://localhost:3000'
        start: npm start
        browser: chrome
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

