# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: adapt

on: push

jobs:
  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint
    - run: npm run test
      env: 
        MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
        SECRETKEY: somesecret109248120938u109
        GOOGLE_CLOUD_PROJECT: adapt-348705
        GCLOUD_STORAGE_BUCKET: adaptstorage350
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
  frontend-checks:
      name: Frontend Checks
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
      steps:
        - uses: actions/checkout@v3
        - run: npm install
        - run: npm run lint

